In [1]:
import numpy as np

In [2]:
import array

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [5]:
np.array([1,2,3,4,5,"prateek" , 4+8j,])

array(['1', '2', '3', '4', '5', 'prateek', '(4+8j)'], dtype='<U64')

In [6]:
np.array([1,2,3,4.5,6.5])             #convert data into float 

array([1. , 2. , 3. , 4.5, 6.5])

In [7]:
np.array([[1,3],[3,4]])         #this is called one darray

array([[1, 3],
       [3, 4]])

In [9]:
np.array([[1,3],[3,4],[6,7]])           #this is called two darray

array([[1, 3],
       [3, 4],
       [6, 7]])

In [10]:
np.array([[1,3],[3,4],[6,7,8]])

C:\Users\Public\Documents\iSkysoft\CreatorTemp/ipykernel_7652/1655787997.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[3,4],[6,7,8]])


array([list([1, 3]), list([3, 4]), list([6, 7, 8])], dtype=object)

In [12]:
np.array([[[1,3],[3,4]],[[1,3],[3,4]]])           #this is called three darray

array([[[1, 3],
        [3, 4]],

       [[1, 3],
        [3, 4]]])

In [14]:
np.array([1,2,3],ndmin = 3)                #give you the bracket

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2, 3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [15]:
np.array([1,2,3],ndmin = 30)              #give you the 30 bracket

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2, 3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [18]:
np.array([1,2,3] , dtype = complex )     

array([1.+0.j, 2.+0.j, 3.+0.j])

In [19]:
np.array([(1,2),(4,5)])     #you have to keep your data form of list or form of tuples both give you simlar kind of output

array([[1, 2],
       [4, 5]])

In [23]:
np.array([(1,2),(4,5)],dtype = [("a",'<i2'), ("b", '<i8')])  

array([(1, 2), (4, 5)], dtype=[('a', '<i2'), ('b', '<i8')])

In [24]:
arr = np.array([(1,2),(4,5)],dtype = [("a",'<i2'), ("b", '<i8')])  

In [26]:
arr[0][0]

1

In [28]:
type(arr[0][0])

numpy.int16

In [35]:
type(arr[0][1])

numpy.int64

In [40]:
arr = np.array([[1,3],[3,4]])

In [41]:
arr

array([[1, 3],
       [3, 4]])

In [42]:
arr[0]

array([1, 3])

In [43]:
arr[0][1]

3

In [48]:
arr[1]

array([3, 4])

In [49]:
type(arr[0][1])

numpy.int32

In [50]:
np.mat(arr)           #change the data numpy to matrix

matrix([[1, 3],
        [3, 4]])

In [51]:
l = [3,4,5,67,7]

In [52]:
np.array(l)

array([ 3,  4,  5, 67,  7])

In [54]:
np.asanyarray(l)      

array([ 3,  4,  5, 67,  7])

In [55]:
mat = np.matrix(arr)

In [56]:
mat

matrix([[1, 3],
        [3, 4]])

In [57]:
np.asanyarray(mat)

matrix([[1, 3],
        [3, 4]])

In [58]:
np.asarray(mat)            #convert into matrix to array

array([[1, 3],
       [3, 4]])

In [59]:
issubclass(np.matrix, np.ndarray)        # it is a issubclass True

True

In [61]:
issubclass(np.ndarray, np.matrix)         #it take false 

False

In [62]:
arr

array([[1, 3],
       [3, 4]])

In [63]:
a = arr

In [64]:
b = np.copy(arr)

In [65]:
arr[0][0] = 67       #change the value of a 

In [66]:
arr

array([[67,  3],
       [ 3,  4]])

In [67]:
a

array([[67,  3],
       [ 3,  4]])

In [68]:
b

array([[1, 3],
       [3, 4]])

In [71]:
arr[0:10]

array([[67,  3],
       [ 3,  4]])

In [72]:
arr[-1]

array([3, 4])

In [73]:
b

array([[1, 3],
       [3, 4]])

In [74]:
for i in arr:
    print(i)

[67  3]
[3 4]


In [75]:
np.fromfunction(lambda i , j :i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [76]:
type(np.fromfunction(lambda i , j :i==j,(4,4)))

numpy.ndarray

In [78]:
np.fromfunction(lambda i , j :i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [79]:
np.fromfunction(lambda i , j :i**j,(4,4))

array([[ 1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  2.,  4.,  8.],
       [ 1.,  3.,  9., 27.]])

In [81]:
np.fromfunction(lambda i , j :i/j,(3,3))

C:\Users\Public\Documents\iSkysoft\CreatorTemp/ipykernel_7652/2281161872.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i , j :i/j,(3,3))
C:\Users\Public\Documents\iSkysoft\CreatorTemp/ipykernel_7652/2281161872.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i , j :i/j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [84]:
[i*i for i in range(5)]

[0, 1, 4, 9, 16]

In [101]:
gen = [i*i for i in range(5)]

In [102]:
def test(x):
    yield x

In [98]:
test

<function __main__.test(x)>

In [104]:
test(5)

<generator object test at 0x000002077B8BC820>

In [105]:
gen 

[0, 1, 4, 9, 16]

In [106]:
np.fromiter(gen,dtype= int)

array([ 0,  1,  4,  9, 16])

In [108]:
np.fromiter(range(5),dtype= int)

array([0, 1, 2, 3, 4])

In [109]:
gen
for i in gen:
    print(i)

0
1
4
9
16


In [111]:
np.fromstring('1,3,5,4,6', sep = ',')

array([1., 3., 5., 4., 6.])

In [112]:
np.fromstring('1,3,5,4,6', sep = ',', dtype= int)

array([1, 3, 5, 4, 6])

In [122]:
np.fromstring("451,552,654,2252" , sep= ",", dtype= complex)       #give you complex,int,bool value

array([ 451.+0.j,  552.+0.j,  654.+0.j, 2252.+0.j])

In [123]:
l = [3,4,5,6,7,8]

In [124]:
np.array(l)

array([3, 4, 5, 6, 7, 8])

In [125]:
arr = np.array(l)

In [130]:
arr1 = np.array([[1,2,3,4], [2,3,4,5],[4,5,6,7]])

In [131]:
arr1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [132]:
type(arr)

numpy.ndarray

In [134]:
arr1.ndim          #give you dimenction

2

In [135]:
arr1.size          #total no. of elements

12

In [136]:
arr1.shape

(3, 4)

In [137]:
arr1.dtype

dtype('int32')

In [138]:
arr.size

6

In [139]:
arr.ndim

1

In [140]:
arr.shape

(6,)

In [148]:
arr2 = np.array([[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]])

In [149]:
arr2

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7]]])

In [150]:
arr2.size             #they are 16 elements

16

In [151]:
arr2.shape

(2, 2, 4)

In [8]:
arr4 = np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]],[[1,2,3,4],[4,5,6,7]]]])

In [9]:
arr4

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 3, 4],
         [4, 5, 6, 7]]]])

In [10]:
arr4.ndim

4

In [159]:
arr4.shape

(1, 4, 2, 4)

In [160]:
arr4.size

32

In [167]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [168]:
np.arange(6.6)               #arange is accept floating 

array([0., 1., 2., 3., 4., 5., 6.])

In [174]:
np.arange(9,6.6,-.3)

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [175]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [178]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [183]:
np.linspace(1,10,5)                #

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [184]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [188]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [189]:
np.zeros((2,5,4,1))

array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]])

In [190]:
np.ones(4)

array([1., 1., 1., 1.])

In [193]:
np.ones((2,3,1))+5

array([[[6.],
        [6.],
        [6.]],

       [[6.],
        [6.],
        [6.]]])

In [194]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [196]:
np.empty((3,4))

array([[0.        , 0.        , 0.        , 1.        ],
       [0.5       , 0.33333333, 2.        , 1.        ],
       [0.66666667, 3.        , 1.5       , 1.        ]])

In [197]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [201]:
np.linspace(2,4,4,endpoint=False)

array([2. , 2.5, 3. , 3.5])

In [204]:
np.linspace(2,4,4,endpoint=False,axis=0)

array([2. , 2.5, 3. , 3.5])

In [207]:
np.linspace([1,6],4,endpoint=False,axis=0)

array([[1.  , 6.  ],
       [1.06, 5.96],
       [1.12, 5.92],
       [1.18, 5.88],
       [1.24, 5.84],
       [1.3 , 5.8 ],
       [1.36, 5.76],
       [1.42, 5.72],
       [1.48, 5.68],
       [1.54, 5.64],
       [1.6 , 5.6 ],
       [1.66, 5.56],
       [1.72, 5.52],
       [1.78, 5.48],
       [1.84, 5.44],
       [1.9 , 5.4 ],
       [1.96, 5.36],
       [2.02, 5.32],
       [2.08, 5.28],
       [2.14, 5.24],
       [2.2 , 5.2 ],
       [2.26, 5.16],
       [2.32, 5.12],
       [2.38, 5.08],
       [2.44, 5.04],
       [2.5 , 5.  ],
       [2.56, 4.96],
       [2.62, 4.92],
       [2.68, 4.88],
       [2.74, 4.84],
       [2.8 , 4.8 ],
       [2.86, 4.76],
       [2.92, 4.72],
       [2.98, 4.68],
       [3.04, 4.64],
       [3.1 , 4.6 ],
       [3.16, 4.56],
       [3.22, 4.52],
       [3.28, 4.48],
       [3.34, 4.44],
       [3.4 , 4.4 ],
       [3.46, 4.36],
       [3.52, 4.32],
       [3.58, 4.28],
       [3.64, 4.24],
       [3.7 , 4.2 ],
       [3.76, 4.16],
       [3.82,

In [208]:
np.linspace([1,6],4,endpoint=False,axis=1)

array([[1.  , 1.06, 1.12, 1.18, 1.24, 1.3 , 1.36, 1.42, 1.48, 1.54, 1.6 ,
        1.66, 1.72, 1.78, 1.84, 1.9 , 1.96, 2.02, 2.08, 2.14, 2.2 , 2.26,
        2.32, 2.38, 2.44, 2.5 , 2.56, 2.62, 2.68, 2.74, 2.8 , 2.86, 2.92,
        2.98, 3.04, 3.1 , 3.16, 3.22, 3.28, 3.34, 3.4 , 3.46, 3.52, 3.58,
        3.64, 3.7 , 3.76, 3.82, 3.88, 3.94],
       [6.  , 5.96, 5.92, 5.88, 5.84, 5.8 , 5.76, 5.72, 5.68, 5.64, 5.6 ,
        5.56, 5.52, 5.48, 5.44, 5.4 , 5.36, 5.32, 5.28, 5.24, 5.2 , 5.16,
        5.12, 5.08, 5.04, 5.  , 4.96, 4.92, 4.88, 4.84, 4.8 , 4.76, 4.72,
        4.68, 4.64, 4.6 , 4.56, 4.52, 4.48, 4.44, 4.4 , 4.36, 4.32, 4.28,
        4.24, 4.2 , 4.16, 4.12, 4.08, 4.04]])

In [209]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [213]:
np.logspace([2,3],4 , axis=1)

array([[  100.        ,   109.8541142 ,   120.67926406,   132.57113656,
          145.63484775,   159.98587196,   175.75106249,   193.06977289,
          212.09508879,   232.99518105,   255.95479227,   281.1768698 ,
          308.88435965,   339.32217719,   372.75937203,   409.49150624,
          449.8432669 ,   494.17133613,   542.86754393,   596.36233166,
          655.12855686,   719.685673  ,   790.60432109,   868.51137375,
          954.09547635,  1048.11313415,  1151.39539933,  1264.85521686,
         1389.49549437,  1526.41796718,  1676.83293681,  1842.06996933,
         2023.58964773,  2222.99648253,  2442.05309455,  2682.69579528,
         2947.05170255,  3237.45754282,  3556.48030622,  3906.93993705,
         4291.93426013,  4714.86636346,  5179.47467923,  5689.86602902,
         6250.55192527,  6866.48845004,  7543.12006335,  8286.42772855,
         9102.98177992, 10000.        ],
       [ 1000.        ,  1048.11313415,  1098.54114199,  1151.39539933,
         1206.79264064,

In [215]:
np.logspace([2],[3], axis=0)

array([[ 100.        ],
       [ 104.81131342],
       [ 109.8541142 ],
       [ 115.13953993],
       [ 120.67926406],
       [ 126.48552169],
       [ 132.57113656],
       [ 138.94954944],
       [ 145.63484775],
       [ 152.64179672],
       [ 159.98587196],
       [ 167.68329368],
       [ 175.75106249],
       [ 184.20699693],
       [ 193.06977289],
       [ 202.35896477],
       [ 212.09508879],
       [ 222.29964825],
       [ 232.99518105],
       [ 244.20530945],
       [ 255.95479227],
       [ 268.26957953],
       [ 281.1768698 ],
       [ 294.70517026],
       [ 308.88435965],
       [ 323.74575428],
       [ 339.32217719],
       [ 355.64803062],
       [ 372.75937203],
       [ 390.69399371],
       [ 409.49150624],
       [ 429.19342601],
       [ 449.8432669 ],
       [ 471.48663635],
       [ 494.17133613],
       [ 517.94746792],
       [ 542.86754393],
       [ 568.9866029 ],
       [ 596.36233166],
       [ 625.05519253],
       [ 655.12855686],
       [ 686.648

In [219]:
d.ndim

1

In [220]:
d = np.linspace(4,7,40)

In [221]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [218]:
d.shape

(40,)

In [228]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [229]:
d.reshape(1,2,1,20)

array([[[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
          4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
          4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
          5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846]],

        [[5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
          5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
          6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
          6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]]])

In [230]:
d.reshape(1,4,10)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
         4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769],
        [4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
         5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846],
        [5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
         5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923],
        [6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
         6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [ ]:
#2:20:00

In [231]:
np.random.rand(3)

array([0.84976784, 0.32727291, 0.91579896])

In [233]:
np.random.randn(5)

array([-0.3371367 ,  0.11991524,  0.23087323, -0.05377884, -0.58115803])

In [235]:
np.random.randn(2,3)           #generate random data 

array([[-1.20487922, -0.11666405, -0.74049418],
       [-1.09090612,  0.20973919, -1.2054115 ]])

In [236]:
np.random.randn(2,2,3)

array([[[ 0.51350786,  0.23080411, -0.61193468],
        [-0.10238092, -0.66045092,  0.03266407]],

       [[-1.4558315 , -0.60519081, -0.22523956],
        [ 0.76616532,  0.93574138, -0.19843875]]])

In [237]:
np.random.randint(5)       #generating a integer

1

In [243]:
np.random.randint(5,60)        #generating a different integer

48

In [247]:
np.random.randint(5,60,  (4,4))

array([[47, 25, 13, 15],
       [27, 37, 11,  7],
       [54, 56, 52,  6],
       [34, 25, 49, 35]])

In [248]:
arr = np.random.randint(3,9, (3,3))

In [249]:
arr

array([[8, 3, 7],
       [4, 6, 5],
       [5, 7, 5]])

In [250]:
arr.reshape(1,9)        # one row and nine column      

array([[8, 3, 7, 4, 6, 5, 5, 7, 5]])

In [251]:
arr.reshape(9,1)               #9 row and one column

array([[8],
       [3],
       [7],
       [4],
       [6],
       [5],
       [5],
       [7],
       [5]])

In [252]:
arr.reshape(1,1,9)            #

array([[[8, 3, 7, 4, 6, 5, 5, 7, 5]]])

In [253]:
arr.reshape(3,3,1)             #3 row and 3 column

array([[[8],
        [3],
        [7]],

       [[4],
        [6],
        [5]],

       [[5],
        [7],
        [5]]])

In [258]:
arr.reshape(3,-5)             #you have to menction any negative number

array([[8, 3, 7],
       [4, 6, 5],
       [5, 7, 5]])

In [259]:
arr.reshape(1,-145654)

array([[8, 3, 7, 4, 6, 5, 5, 7, 5]])

In [260]:
arr

array([[8, 3, 7],
       [4, 6, 5],
       [5, 7, 5]])

In [262]:
arr.max()

8

In [263]:
arr.min()

3

In [13]:
arr = np.random.randint(4,10, (5,5))

In [14]:
arr

array([[6, 4, 7, 9, 7],
       [9, 9, 7, 5, 6],
       [7, 6, 8, 6, 4],
       [9, 5, 6, 7, 6],
       [8, 9, 7, 7, 8]])

In [15]:
arr[3: , 3:]

array([[7, 6],
       [7, 8]])

In [16]:
arr[1:, [1,3]]           #take arr data

array([[9, 5],
       [6, 6],
       [5, 7],
       [9, 7]])

In [17]:
arr[:, [1,3]]

array([[4, 9],
       [9, 5],
       [6, 6],
       [5, 7],
       [9, 7]])

In [18]:
#2:35:56

In [20]:
arr

array([[6, 4, 7, 9, 7],
       [9, 9, 7, 5, 6],
       [7, 6, 8, 6, 4],
       [9, 5, 6, 7, 6],
       [8, 9, 7, 7, 8]])

In [26]:
arr[arr<10]

array([6, 4, 7, 9, 7, 9, 9, 7, 5, 6, 7, 6, 8, 6, 4, 9, 5, 6, 7, 6, 8, 9,
       7, 7, 8])

In [28]:
arr>10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [29]:
arr * arr

array([[36, 16, 49, 81, 49],
       [81, 81, 49, 25, 36],
       [49, 36, 64, 36, 16],
       [81, 25, 36, 49, 36],
       [64, 81, 49, 49, 64]])

In [46]:
arr1 = np.random.randint(2,4,(3,3))

In [47]:
arr1

array([[2, 3, 3],
       [3, 2, 3],
       [3, 2, 2]])

In [53]:
arr2 = np.random.randint(2,4,(3,3))              #dimenction should be same 

In [54]:
arr2

array([[2, 2, 2],
       [2, 2, 2],
       [3, 2, 2]])

In [55]:
arr1*arr2              #they multipli arr1*arr2

array([[4, 6, 6],
       [6, 4, 6],
       [9, 4, 4]])

In [56]:
arr1@arr2

array([[19, 16, 16],
       [19, 16, 16],
       [16, 14, 14]])

In [57]:
arr/0      #show the infinity

C:\Users\Public\Documents\iSkysoft\CreatorTemp/ipykernel_4612/4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [58]:
arr**2

array([[36, 16, 49, 81, 49],
       [81, 81, 49, 25, 36],
       [49, 36, 64, 36, 16],
       [81, 25, 36, 49, 36],
       [64, 81, 49, 49, 64]], dtype=int32)

In [76]:
arr = np.zeros((3,4))

In [77]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [81]:
a = np.array([1,2,3,5])

In [82]:
a

array([1, 2, 3, 5])

In [83]:
arr + a            # it is add with arr + a data 

array([[1., 2., 3., 5.],
       [1., 2., 3., 5.],
       [1., 2., 3., 5.]])

In [84]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [85]:
9b = np.array([5,6,7])

In [86]:
b

array([5, 6, 7])

In [89]:
b.reshape(3,1)  + arr   

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [91]:
b.T                    #transpose data 

array([5, 6, 7])

In [93]:
b = np.array([[5,6,7]])

In [99]:
b.T + arr

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [100]:
arr = np.random.rand(5,4)

In [101]:
arr

array([[0.90122049, 0.41650539, 0.55695911, 0.71817581],
       [0.33804335, 0.72581958, 0.42607058, 0.93962008],
       [0.39808091, 0.07550943, 0.26423627, 0.07691865],
       [0.38290429, 0.43147965, 0.50568545, 0.68147749],
       [0.14722914, 0.72387857, 0.09920439, 0.57520953]])

In [102]:
np.sqrt(arr)           #it is square value

array([[0.94932634, 0.64537229, 0.74629693, 0.84745254],
       [0.58141496, 0.85195046, 0.65274082, 0.96934002],
       [0.63093653, 0.27478979, 0.51403917, 0.27734212],
       [0.61879261, 0.65687111, 0.71111564, 0.8255165 ],
       [0.38370449, 0.85081054, 0.31496729, 0.75842569]])

In [103]:
np.exp(arr)

array([[2.46260687, 1.51665218, 1.74535698, 2.05068895],
       [1.40220129, 2.06642401, 1.53122884, 2.55900902],
       [1.4889645 , 1.0784334 , 1.30243588, 1.07995422],
       [1.46653766, 1.53953382, 1.65812169, 1.97679628],
       [1.15861942, 2.06241694, 1.10429199, 1.77750293]])

In [104]:
np.log10(arr)

array([[-0.04516894, -0.38037937, -0.25417669, -0.14376923],
       [-0.4710276 , -0.13917132, -0.37051846, -0.02704771],
       [-0.40002865, -1.1219988 , -0.57800758, -1.11396834],
       [-0.41690977, -0.36503968, -0.29611954, -0.16654848],
       [-0.83200623, -0.14033428, -1.0034691 , -0.24017393]])

In [106]:
arr1 = np.random.randint(2,5, (5,5))

In [107]:
arr1

array([[4, 3, 2, 3, 4],
       [4, 3, 3, 2, 4],
       [4, 4, 3, 4, 4],
       [3, 3, 3, 3, 2],
       [2, 3, 4, 2, 3]])

In [108]:
np.log10(arr1)       #log condition

array([[0.60205999, 0.47712125, 0.30103   , 0.47712125, 0.60205999],
       [0.60205999, 0.47712125, 0.47712125, 0.30103   , 0.60205999],
       [0.60205999, 0.60205999, 0.47712125, 0.60205999, 0.60205999],
       [0.47712125, 0.47712125, 0.47712125, 0.47712125, 0.30103   ],
       [0.30103   , 0.47712125, 0.60205999, 0.30103   , 0.47712125]])

In [115]:
np.random.seed(13)
np.random.rand(2,4)

array([[0.77770241, 0.23754122, 0.82427853, 0.9657492 ],
       [0.97260111, 0.45344925, 0.60904246, 0.77552651]])

In [116]:
np.random.seed(30)
np.random.rand(2,4)

array([[0.64414354, 0.38074849, 0.66304791, 0.16365073],
       [0.96260781, 0.34666184, 0.99175099, 0.2350579 ]])